//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_dotNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail_orders
    {
        public int orders_id { get; set; }
        public int product_id { get; set; }
        public string quantity { get; set; }
        public string size { get; set; }
    
        public virtual order order { get; set; }
        public virtual product product { get; set; }
    }
}
